//Find
	REWARD_BOX_UNIQUE_ITEM_CAPE_OF_COURAGE = 76007,
	
///Add
#if defined(BL_PRIVATESHOP_SEARCH_SYSTEM)
	PRIVATE_SHOP_SEARCH_LOOKING_GLASS = 60004,
	PRIVATE_SHOP_SEARCH_TRADING_GLASS = 60005,
#endif